# Gram-Schmidt and Modified Gram-Schmidt

In [1]:
import numpy as np
import numpy.linalg as la

In [2]:
A = np.random.randn(3, 3)

In [3]:
def test_orthogonality(Q):
    print("Q:")
    print(Q)
    
    print("Q^T Q:")
    QtQ = np.dot(Q.T, Q)
    QtQ[np.abs(QtQ) < 1e-15] = 0
    print(QtQ)

In [35]:
Q = np.zeros(A.shape)

Now let us generalize the process we used for three vectors earlier:

In [37]:
#clear

for k in range(A.shape[1]):
    avec = A[:, k]
    q = avec
    for j in range(k):
        #为什么 j 要在 k 里面 循环？
        q = q - np.dot(avec, Q[:,j])*Q[:,j]
        #q的每一行等于前一行的q 减去 
    Q[:, k] = q/la.norm(q)


0 [-0.77941469 -0.56572395 -0.26920096]
1 [-0.46875034  0.8116626  -0.34853543]
2 [-0.41567519  0.14546559  0.89780505]


This procedure is called [Gram-Schmidt Orthonormalization](https://en.wikipedia.org/wiki/Gram–Schmidt_process).

Now let us try a different example ([Source](http://fgiesen.wordpress.com/2013/06/02/modified-gram-schmidt-orthogonalization/)):

In [2]:

np.set_printoptions(precision=13)

eps = 1e-8

A = np.array([
    [1,  1,  1],
    [eps,eps,0],
    [eps,0,  eps]
    ])

A

array([[  1.0000000000000e+00,   1.0000000000000e+00,   1.0000000000000e+00],
       [  1.0000000000000e-08,   1.0000000000000e-08,   0.0000000000000e+00],
       [  1.0000000000000e-08,   0.0000000000000e+00,   1.0000000000000e-08]])

In [3]:
Q = np.zeros(A.shape)

In [38]:
for k in range(A.shape[1]):
    avec = A[:, k]
    q = avec
    for j in range(k):
        q = q - np.dot(avec, Q[:,j])*Q[:,j]
    q = q/la.norm(q)
    Q[:, k] = q
    print("norm -->", q)
    print("-------")

norm --> [-0.46875034  0.8116626  -0.34853543]
-------
norm --> [-0.41567519  0.14546559  0.89780505]
-------
norm --> [-0.77941469 -0.56572395 -0.26920096]
-------


In [43]:
test_orthogonality(Q)

Q:
[[  1.0000000000000e+00   0.0000000000000e+00   0.0000000000000e+00]
 [  1.0000000000000e-08   0.0000000000000e+00  -7.0710678118655e-01]
 [  1.0000000000000e-08  -1.0000000000000e+00  -7.0710678118655e-01]]
Q^T Q:
[[  1.0000000000000e+00  -1.0000000000000e-08  -1.4142135623731e-08]
 [ -1.0000000000000e-08   1.0000000000000e+00   7.0710678118655e-01]
 [ -1.4142135623731e-08   7.0710678118655e-01   1.0000000000000e+00]]


Questions:

* What happened?
* How do we fix it?

In [44]:
Q = np.zeros(A.shape)

In [39]:
#clear
for k in range(A.shape[1]):
    q = A[:, k]
    for j in range(k):
        q = q - np.dot(q, Q[:,j])*Q[:,j]
    
    Q[:, k] = q/la.norm(q)

In [40]:
test_orthogonality(Q)

Q:
[[-0.46875034 -0.41567519 -0.77941469]
 [ 0.8116626   0.14546559 -0.56572395]
 [-0.34853543  0.89780505 -0.26920096]]
Q^T Q:
[[ 1.00000000e+00  0.00000000e+00 -1.04590696e-15]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [-1.04590696e-15  0.00000000e+00  1.00000000e+00]]


This procedure is called *Modified* Gram-Schmidt Orthogonalization.

Questions:

* Is there a difference mathematically between modified and unmodified?
* Why are there $10^{-8}$ values left in $Q^TQ$?